export GOROOT := $(shell go env GOROOT)
export PATH := $(GOROOT)/bin:$(GOPATH)/bin:$(PATH)
export GO111MODULE=on
LDFLAGS := -s -w

os-archs=windows:386 windows:amd64 darwin:amd64 darwin:arm64 freebsd:386 freebsd:amd64 linux:386 linux:amd64 linux:arm linux:arm64 linux:mips64 linux:mips64le linux:mips:softfloat linux:mipsle:softfloat

all: build

build: app

app:
	@mkdir -p ./release
	@$(foreach n, $(os-archs),\
		os=$(shell echo "$(n)" | cut -d : -f 1);\
		arch=$(shell echo "$(n)" | cut -d : -f 2);\
		gomips=$(shell echo "$(n)" | cut -d : -f 3);\
		target_suffix=$${os}_$${arch};\
		ext="";\
		if [ "$${os}" = "windows" ]; then ext=".exe"; fi;\
		echo "Build $${os}-$${arch}...";\
		env CGO_ENABLED=0 GOOS=$${os} GOARCH=$${arch} GOMIPS=$${gomips} go build -ldflags "$(LDFLAGS)" -o ./release/HustWebAuth_$${target_suffix}$${ext} ./;\
		echo "Build $${os}-$${arch} done";\
	)
